# Generated by Django 3.1 on 2020-09-02 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Tipos')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('pc', models.IntegerField(verbose_name='PC')),
                ('ps', models.IntegerField(verbose_name='PS')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='pokemon')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.region')),
                ('tipos', models.ManyToManyField(to='datos.Tipo')),
            ],
            options={
                'verbose_name': 'Pokemon',
                'verbose_name_plural': 'Bichos',
                'ordering': ['name'],
            },
        ),
    ]
