# Generated by Django 3.1 on 2020-09-02 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pokemon',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='tipo',
            unique_together={('name',)},
        ),
    ]
